[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eqx_marl"
version = "0.0.1"
description = ""
authors = [
    { name = "John Viljoen", email = "johnviljoen2@gmail.com" },
]

readme = "README.md"

dependencies = [
    "matplotlib",
    "tqdm",
    "jax",
    "equinox",
    "distreqx",
    "brax"
]

[tool.setuptools.packages.find]
where = [
    "src"
]

